debian10.rubyci.org: &default
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

# ArchLinux
chkbuild006.hsbt.org:
  <<: *default

icc.rubyci.org:
  <<: *default

freebsd12.rubyci.org:
  <<: *default

# OpenBSD 6.6 (beta)
178.128.102.12:
  <<: *default

# Fedora 31 x86_64
fedora31.rubyci.org:
  <<: *default

centos6.rubyci.org:
  <<: *default

centos7.rubyci.org:
  <<: *default

debian8.rubyci.org:
  <<: *default

debian9.rubyci.org:
  <<: *default

debian.rubyci.org:
  <<: *default

ubuntu1604.rubyci.org:
  <<: *default

ubuntu1804.rubyci.org:
  <<: *default

ubuntu.rubyci.org:
  <<: *default

# (OpenCSW) Solaris 10x / Solaris 11x / Solaris 10s / Solaris 11s
login.opencsw.org:
  ssh_options:
    user: rubyci
  properties:
    sudo_required: false
    run_list:
      - recipes/opencsw.rb
