# Debian 8.8 x86_64
chkbuild004.hsbt.org: &default
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

# ArchLinux
chkbuild006.hsbt.org:
  <<: *default

# icc16-x64
chkbuild008.hsbt.org:
  <<: *default

# Fedora 28 x86_64
chkbuild011.hsbt.org:
  <<: *default

# CentOS 6.9 x86_64
chkbuild012.hsbt.org:
  <<: *default

# OpenBSD 6.6 (beta)
178.128.102.12:
  <<: *default

# Fedora 31 x86_64
fedora31.rubyci.org:
  <<: *default

# (OpenCSW) Solaris 10x / Solaris 11x / Solaris 10s / Solaris 11s
login.opencsw.org:
  ssh_options:
    user: rubyci
  properties:
    sudo_required: false
    run_list:
      - recipes/opencsw.rb
